import type React from "react"
import { Toaster } from "@/components/ui/sonner"
import "@/styles/globals.css"
import type { Metadata } from "next"
import { Inter } from "next/font/google"
import { ThemeProvider } from "next-themes"
import { currentUser } from "./lib/auth"
import Providers from "./providers/SessionProvider"
import { MobileSimulatorProvider } from "./components/MobileSimulator/provider/MobileSimulatorContext"
import { UserProvider } from "./hooks/UserProvider"
import { CartProvider } from "@/contexts/CartContext"
import { ToastProvider } from "./providers/toast-provider"

const inter = Inter({ subsets: ["latin"] })

export const metadata: Metadata = {
  title: {
    default: "Next Dashboard | Zulmy Azhary",
    template: "Next Dashboard | %s",
  },
  description: "Generated by create next app",
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const user = await currentUser()

  if (!user) {
    return (
      <html lang="en" className="h-full">
        <body className={inter.className}>
          <Toaster position="bottom-left" richColors theme="light" />
          <Providers>
            <MobileSimulatorProvider>
              <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
                <UserProvider>
                  <CartProvider>
                    <div className="flex-1 w-full overflow-auto">{children}</div>
                  </CartProvider>
                </UserProvider>
                <ToastProvider />
              </ThemeProvider>
            </MobileSimulatorProvider>
          </Providers>
        </body>
      </html>
    )
  }

  return (
    <html lang="en" className="h-full">
      <body className={inter.className}>
        <Toaster position="bottom-left" richColors theme="light" />
        <Providers>
          <MobileSimulatorProvider>
            <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
              <UserProvider>
                <CartProvider>
                  <div className="flex-1 w-full overflow-auto">{children}</div>
                </CartProvider>
              </UserProvider>
              <ToastProvider />
            </ThemeProvider>
          </MobileSimulatorProvider>
        </Providers>
      </body>
    </html>
  )
}
